### ISSUE TITLE
Add other authors' names in source file headers

### ISSUE THREAD

**Issue by Argentus** [Argentus/uEliece#1]
libuEliece/src/uEliece.c
libuEliece/src/uEliece.h
libuEliece/src/uEliece-settings.h
libuEliece/src/uEliece-utils.h

**Comment by obernat** [comment]
Preco by som to robil?

**Comment by Argentus** [comment]
Akoze mozme to spravit aj postupne, ked ludia spravia nejaku zmenu do tych suborov, to je pravda
